steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy my-app --image gcr.io/just-compare-backend/compare-app:$latest,v0.1.0 --region us-central1 --platform managed --allow-unauthenticated
