apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/just-compare-backend/just-compare-backend
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: e632920c-8bb7-4980-8b5b-6ccffc550d4c
  labels:
    cloud.googleapis.com/location: us-central1
  name: just-compare-backend
  namespace: '999298140975'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        client.knative.dev/user-image: gcr.io/just-compare-backend/just-compare-backend
        run.googleapis.com/client-name: Cloud Code for VS Code
        run.googleapis.com/client-version: 1.21.3
      name: just-compare-backend-00001-jey
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/just-compare-backend/just-compare-backend
        ports:
        - containerPort: 5001
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 256Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 5001
          timeoutSeconds: 240
      serviceAccountName: 999298140975-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
