apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - image: gcr.io/just-compare-backend/compare-app
          ports:
            - name: http1
              containerPort: 5001
