name: Build and Push Python Image to Google Cloud Platform # name of the workflow
on:    # The trigger for workflow
  push:
    branches: [ main ]

jobs:  #groups together all the jobs
  build-push-gcr:  #the job name
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: compare-app
      PROJECT_ID: just-compare-backend
    steps:    #groups together all the steps that run in build-push-gcr
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@v0 #using actions created by google
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true #exports the credentials service account key and project id
      #this steps authenticate docker with container registry

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
